server:
  port: 8443

spring:
    datasource:
            url: jdbc:mysql://127.0.0.1:3307/lxddesign?characterEncoding=UTF-8&serverTimezone=UTC
            username: root
            password: 203567
            driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
          ddl-auto: none
      database-platform: org.hibernate.dialect.MySQLDialect
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


